### ISSUE TITLE
prior mask generation

### ISSUE THREAD

**Issue by hflsdupont** [MVIG-SJTU/DIRV#1]
Hi, 

When I try to execute your **demo.py** using the pre-trained model, it asks for **new_prior_mask.pkl**. How should I generate this file? It looks like the original v-coco does not come up with it. 

Thanks!

**Comment by yichen928** [comment]
Sorry, I forgot it. 
Please check the ReadMe again. I have uploaded this file. Each element inside it refers to the prior probability that a verb (e.g. eat) is associated with an object category (e.g. apple).

**Comment by Yichen-Xie** [comment]
Sorry, I forgot it. 
Please check the ReadMe again. I have uploaded this file. Each element inside it refers to the prior probability that a verb (e.g. eat) is associated with an object category (e.g. apple).
