### ISSUE TITLE
Train a sub data of VCOCO/HICO-Det

### ISSUE THREAD

**Issue by JackKoLing** [MVIG-SJTU/DIRV#2]
Beautiful work. My memory and gpu resources are insufficient, so I want to ask **if I can only select a small part of data when training** (e.g. 2000 images of Vcoco for training), because I just want to run through the whole procedure. If possible, please give some tips  to modify it. Thank you again.

**Comment by yichen928** [comment]
I think you should modify the dataloaders by randomly choosing some items in "self.ann_by_image" (efficientdet/hico_det_dataset.py) and "self.image_ids" (efficientdet/vcoco_dataset.py)  separately for the two datasets after the data is loaded.

There is also a simpler method for V-COCO dataset. You can directly modify "datasets/vcoco/data/splits/vcoco_trainval.ids" by sampling some ids inside it.

You should ensure that all the interaction categories appear in your selected training samples.

**Comment by JackKoLing** [comment]
> I think you should modify the dataloaders by randomly choosing some items in "self.ann_by_image" (efficientdet/hico_det_dataset.py) and "self.image_ids" (efficientdet/vcoco_dataset.py) separately for the two datasets after the data is loaded.
> 
> There is also a simpler method for V-COCO dataset. You can directly modify "datasets/vcoco/data/splits/vcoco_trainval.ids" by sampling some ids inside it.
> 
> You should ensure that all the interaction categories appear in your selected training samples.

Thank you!
