### ISSUE TITLE
COCO-related problem

### ISSUE THREAD

**Issue by Touger** [MVIG-SJTU/DIRV#3]
Hi!
Thanks for sharing the code. I am trying to train the network, however, there are some problems related to COCO dataset happened.

Traceback (most recent call last):
  File "train.py", line 510, in <module>
    train(opt)
  File "train.py", line 169, in train
    training_set = VCOCO_Dataset(root_dir="./datasets/vcoco", set=params.train_set, color_prob=1,
  File "/remote-home/DATA8_DB12/data/projects/DIRV/DIRV-main/efficientdet/vcoco_dataset.py", line 51, in __init__
    self.coco = COCO(os.path.join(self.root_dir, "coco/annotations", "instances_trainval2014.json"))
  File "/DB/rhome/anaconda3/lib/python3.8/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: './datasets/vcoco/coco/annotations/instances_trainval2014.json'

I can't find this annotation file in COCO offical website, could you tell me where I can find it?

Thanks a lot.

**Comment by Fang-Haoshu** [comment]
Hi, you ca find it here
http://images.cocodataset.org/annotations/annotations_trainval2014.zip

**Comment by Touger** [comment]
> Hi, you ca find it here
> http://images.cocodataset.org/annotations/annotations_trainval2014.zip

Thanks for your reply. However, There is no **instances_trainval2014.json** in this zip file.

**Comment by yichen928** [comment]
> > Hi, you ca find it here
> > http://images.cocodataset.org/annotations/annotations_trainval2014.zip
> 
> Thanks for your reply. However, There is no **instances_trainval2014.json** in this zip file.

Sorry, I think we used the dataset processed by some other work. You can just combine "instances_train2014.json" and "instances_val2014.json" to get "instances_trainval2014.json". Or you can download it from our google drive: https://drive.google.com/drive/folders/14xXUb5l_SugfWiRXX3o8jgKXMNac1c7_?usp=sharing
Thank you for pointing it out!
