### ISSUE TITLE
Ask variable “num_inst_action=234”

### ISSUE THREAD

**Issue by JackKoLing** [MVIG-SJTU/DIRV#4]
Hi, i try to train my dataset. I know **"num_union_action=117"** mean the hico-det verb numbers. But i don't know what's the mean of  "**num_inst_action=234**"  in HICO-det dataset. Could you explain about it? How can i set the number? Thank you!

**Comment by yichen928** [comment]
Hi, we consider the actions of humans and objects as different actions when it comes to instance actions in the instance detector.
Take an action "kick" as example. For humans, it is "kick", and for objects (i.e. balls) the action is "be kicked". Then, we can get 117*2=234 instance actions.

**Comment by JackKoLing** [comment]
> Hi, we consider the actions of humans and objects as different actions when it comes to instance actions in the instance detector.
> Take an action "kick" as example. For humans, it is "kick", and for objects (i.e. balls) the action is "be kicked". Then, we can get 117*2=234 instance actions.

I see. Thank you. Close it.
