### ISSUE TITLE
Script for heat map visualization in paper

### ISSUE THREAD

**Issue by JackKoLing** [MVIG-SJTU/DIRV#6]
Thank you for your wonderful work. In the paper, the object location distribution in Figure 3 is very convincing. Could you please provide the corresponding visualization script? Thanks

**Comment by yichen928** [comment]
Hi, you can refer to the following code. Maybe you should make some modifications based on your requirement.
[show_density.zip](https://github.com/MVIG-SJTU/DIRV/files/6377424/show_density.zip)
