### ISSUE TITLE
请问如何对任意一个图像验证DIRV demo?

### ISSUE THREAD

**Issue by ahong007007** [MVIG-SJTU/DIRV#7]
感谢您的工作和开源，让研究HOI更进一步。

我在使用过程中发现1个问题(图形是VCOCO之外的任意图像，主要看对显示世界的泛化能力):
python demo.py --image_path /path/to/a/single/image

提示没有new_prior_mask.pkl文件，如果用vcoco的new_prior_mask.pkl，又会报出一堆错误来。

new_prior_mask.pkl文件作用是什么？ 在推理的阶段，是不是还需要什么先验条件？谢谢您。
```

File "/root/anaconda3/envs/py37_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for EfficientDetBackbone:
        size mismatch for union_branch.action_classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([1053, 160, 1, 1]) from checkpoint, the shape in current model is torch.Size([225, 160, 1, 1]).
        size mismatch for union_branch.action_classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([1053]) from checkpoint, the shape in current model is torch.Size([225]).
        size mismatch for instance_branch.action_classifier.header.pointwise_conv.conv.weight: copying a param with shape torch.Size([2106, 160, 1, 1]) from checkpoint, the shape in current model is torch.Size([459, 160, 1, 1]).
        size mismatch for instance_branch.action_classifier.header.pointwise_conv.conv.bias: copying a param with shape torch.Size([2106]) from checkpoint, the shape in current model is torch.Size([459]).
(py37_cuda101) [root@object-detection-03 DIRV]# vim datasets/vcoco/new_prior_mask.pkl
```

**Comment by Fang-Haoshu** [comment]
new_prior_mask.pkl在readme中有介绍，应当载入vcoco的
这个报错是指载入的模型文件错误，与pkl无关，可以检查一下是否载入的模型不对

**Comment by ahong007007** [comment]
> new_prior_mask.pkl在readme中有介绍，应当载入vcoco的
> 这个报错是指载入的模型文件错误，与pkl无关，可以检查一下是否载入的模型不对

感谢您的回复，我从新设置了一下环境，现在可以正常运行，但是又有了新的问题，^_^

1.运行demo，只有人和动作的检测，貌似没有人实现<human verb object>三元组的输出。
![1](https://user-images.githubusercontent.com/22077027/133051943-fdb8fceb-b9b5-4311-bc68-308acaf4756b.jpg)

 CUDA_VISIBLE_DEVICES=0 python demo.py --weights vcoco_best.pth   --image_path 
 /local_data/hoi/1707510278359900/out00150.jpg  --save_path ./1.jpg

**Comment by yichen928** [comment]
demo.py使用的在vcoco上预训练的模型只能分辨vcoco中的20多种hoi，上面这张图片种貌似并没有非常明显的这些hoi，所以检测效果一般（可以看到预测confidence都比较低，一般1以下confidence都不太可靠）。
demo.py会通过颜色体现出三元组，对应的动作标签和目标物体边界框颜色相同。下面这张图片例子更加明显，三个ski标签颜色不同，分别与滑板边界框颜色对应。
![image](https://user-images.githubusercontent.com/48796750/133350728-2ee6b7de-bac1-44f0-a9a1-651d463e8f08.png)

**Comment by ahong007007** [comment]
谢谢您的精彩回复。

请问<人体，目标，动作>三元组会保存下来吗？如果保存会有什么样的格式解析？

**Comment by yichen928** [comment]
目前demo.py没有保存，你可以根据我们的visualize自行简单地修改代码将其保存下来
