### ISSUE TITLE
demo code

### ISSUE THREAD

**Issue by batooooo** [MVIG-SJTU/DIRV#8]
Hi 
I want to show it as an 'action_object' in the demo code. What should I do?

**Comment by yichen928** [comment]
Hi, you can find the predicted object category in 
https://github.com/MVIG-SJTU/DIRV/blob/b704f263cafd452cbccdc321668c58d28b2b0c21/demo.py#L339
The associated category names are in projects/vcoco.yml.

You can try to add the category name to the output by yourself.

**Comment by batooooo** [comment]
thanks a lot!
Can i ask some questions?

I'd like to ask you what action_value[4] means in the visual.py, what is the scope of it, and how it differs from confidence score?

**Comment by yichen928** [comment]
I think action_value[4] is exactly the confidence score. Notice that we did nót normalize it to the range 0-1. Theoretically, it should be greater than zero and has no upper bound. You may refer to our paper for its calculation.
